# Users
GET http://localhost:3000/users

###
POST  http://localhost:3000/auth/signup
Content-Type: application/json
Accept: application/json

{
    "username": "Prince Godwyll",
    "email": "godwyllprince@gmail.com",
    "password": "12345678"
}

###
POST http://localhost:3000/otp/verify/signup
Content-Type: application/json

{
  "userId": "cmluz63ls0000r0n6n0zmfp0x",
  "code": "846042"
}

###
GET http://localhost:3000

###
POST http://localhost:3000/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "godwyllprince@gmail.com",
    "password": "12345678"
}


###
GET http://localhost:3000/auth/profile/cmlmygzlk0000kpn63jfgokpu
Content-Type: application/json
Accept: application/json
Authorization: Bearer 